### ISSUE TITLE
絵文字3つ以上含む発言をチャットに送信すると他人がフリーズする

### ISSUE THREAD

**Issue by yadu-ki** [TK11235/udonarium#1]
## 現象
- 絵文字を3文字以上含む発言を行うと、発言者以外のチャットウィンドウにて新しい発言が「From:」のみ表示される状態になる。
- この症状が発生したとき、更に「メインタブを表示しているチャットウィンドウが操作を受け付けない」または「メニューのボタンをクリックして新しいウィンドウを出す・チャットウィンドウでチャットタブを切り替えるなどの操作を受け付けない」などの症状が発生した。適切な表現かどうか迷うが、以下この症状を「フリーズ」と表記する。
- 初めてこの現象を確認した際、フリーズ症状が発生した参加者のブラウザはFirefox 55.0.3 (64 ビット), Google Chrome 60.0.3112.113（Official Build） 64ビット。絵文字送信者のブラウザはGoogle Crome 60.0.3112.113（Official Build） 32 ビット。
- 初めてこの現象を確認した日時は2017年9月9日14時頃、場所は https://udonarium.taruki.com/ 。

## 再現手順
1. ルーム機能でもPeerID直接入力でもいいので、ユーザーAとユーザーBが接続する。
2. ユーザーAがチャットのメインタブに「🐎🏇🐴」と送信する。
3. ユーザーBのユドナリウムにて、「🐎🏇🐴」受信以降の発言が全て「From:」の文字のみ表示される状態になる。新しくチャットウィンドウを表示すると異常な表示になる。このとき、ユーザーAのユドナリウムは正常動作し続ける。

## その他、確認したこと
- unicodeとはいえ絵文字が原因だろうと考え、該当の馬絵文字を含めいくつかの絵文字を送受信する実験を行った。使用ブラウザはFirefox 55.0.3 (64 ビット)。
- 馬絵文字を1文字ずつ送信したところ、受信者側は新規発言を受信しなかった。
- 2文字ずつ送信したところ、やはり受信者側は新規発言を受信しなかった。
- 3文字以上送信すると、再現手順3の症状が発生した。
- 絵文字と絵文字の間にスペースや他の文字列（「あああああ」等）を含めても同様であった。
- また、送受信できる絵文字とできない絵文字が存在することを確認した。具体的には、Dingbatsは送受信に成功したが、EmoticonsとMiscellaneous Symbols And Pictographsでは症状が発生した。
- 確実に発生する症状は再現手順3に記述したもののみで、フリーズ症状は再現しない場合がある。フリーズ症状の発生率はデータが蓄積されているほど高いと感じた。
- コンソールを確認したところ、絵文字3文字以上含む発言を受信した時には「this.attributes is undefined」というエラーが発生している。

馬絵文字を用いて1文字〜6文字まで実験した際のchat.xml内容を記す。
実験内容は、上記再現手順「2」の段階で発言する内容を「🐎」「🐎🏇」「🐎🐴」「🏇🐴」「🐎🏇🐴」「🐎🏇🐴🐎」「🐎🏇🐴🐎🏇」「🐎🏇🐴🐎🏇🐴」に変更したものである。

### 送信者側
```
<chat-tab-list>
  <chat-tab name="メインタブ">
    <chat from="GTFU-PKCA-RYCXVVQL" name="プレイヤー" timestamp="1505024713893" imageIdentifier="none_icon">🐎</chat>
    <chat from="GTFU-PKCA-RYCXVVQL" name="プレイヤー" timestamp="1505024715355" imageIdentifier="none_icon">🐎🏇</chat>
    <chat from="GTFU-PKCA-RYCXVVQL" name="プレイヤー" timestamp="1505024718381" imageIdentifier="none_icon">🐎🐴</chat>
    <chat from="GTFU-PKCA-RYCXVVQL" name="プレイヤー" timestamp="1505024719675" imageIdentifier="none_icon">🏇🐴</chat>
    <chat from="GTFU-PKCA-RYCXVVQL" name="プレイヤー" timestamp="1505024721218" imageIdentifier="none_icon">🐎🏇🐴</chat>
    <chat from="GTFU-PKCA-RYCXVVQL" name="プレイヤー" timestamp="1505024726790" imageIdentifier="none_icon">🐎🏇🐴🐎</chat>
    <chat from="GTFU-PKCA-RYCXVVQL" name="プレイヤー" timestamp="1505024728054" imageIdentifier="none_icon">🐎🏇🐴🐎🏇</chat>
    <chat from="GTFU-PKCA-RYCXVVQL" name="プレイヤー" timestamp="1505024729392" imageIdentifier="none_icon">🐎🏇🐴🐎🏇🐴</chat>
  </chat-tab>
  <chat-tab name="サブタブ"></chat-tab>
</chat-tab-list>
```

### 受信者側
```
<chat-tab-list>
  <chat-tab name="メインタブ">
    <chat>ߐ꡴tri</chat>
    <chat>ߐߐttribu</chat>
    <chat>ߐߐattribute</chat>
  </chat-tab>
  <chat-tab name="サブタブ"></chat-tab>
</chat-tab-list>
```

## 期待すること
- 上記「送信者側」のログは上記実験時に期待した動作そのものであるため、これが受信者側にも反映されるように動作すること。
- もしくは、使ってはいけない文字・文字列がある場合、チュートリアル等で説明されること。

**Comment by TK11235** [comment]
報告ありがとうございます。

現象を再現できることを確認しました。  
データ送受信の際に実行されるBinaryPackシリアライズで、絵文字を含むデータの符号化／復号化に失敗していました。

絵文字が正常に受信側に送信されるように修正してみます。

このIssueは修正をコミットしたのち閉じる予定です。
