### ISSUE TITLE
「ユドナリウム」の権利に関しまして

### ISSUE THREAD

**Issue by issei0124** [TK11235/udonarium#130]
TK11235様

初めまして。
連絡先がTwitterかこちらでしたのでお送りさせて頂きました。
ユドナリウムの権利について確認させて頂きたいことがございます。

現在ユドナリウムを動画配信サービスにての使用を検討しております。
媒体はニコニコ動画でニコニコチャンネルにての配信を考えております。
ニコニコチャンネルは月額利用料を支払ったユーザーが見れる
サービスとなっておりますので有料放送となります。

上記想定にて使用させていただくことは可能でしょうか？

ご確認のほどよろしくお願い申し上げます。

**Comment by TK11235** [comment]
Twitterの方に回答を記載しました。
https://twitter.com/TK11235/status/1298258771823583233

このIssueはCIoseとします。
