### ISSUE TITLE
Prototype Pollution

### ISSUE THREAD

**Issue by SavageChieftain** [TK11235/udonarium#136]
Hi, TK.
I have found a vulnerability in your product.
It's a technique called "Prototype Pollution" that happens when you copy a js object.

- [Japanese lang blog post about Prototype Pollution](https://jovi0608.hatenablog.com/entry/2018/10/19/083725) :)

https://github.com/TK11235/udonarium/blob/d8bc74fcca7602e5b1cef8d713879e8ef2b5eae5/src/app/service/app-config.service.ts#L148

I don't think you need to create a hotfix right now.
(It's settings aren't used in the app now.

But I think it's better to fix it as soon as possible.

It's a similar story, `object-path` has the same problem. 
When creating a package, use `npm audit fix` before building.

- Dependencies tree

```
@angular-devkit/build-angular > resolve-url-loader > adjust-sourcemap-loader > object-path
```

chao!

**Comment by TK11235** [comment]
v1.12.1のリリースで修正したためCloseします。
