### ISSUE TITLE
Serious Security issues

### ISSUE THREAD

**Issue by zeteticl** [TK11235/udonarium#146]
in udonarium, 
SkyWay API key is public by console,
the room password is not  encryption 
and  https://udonarium.app/ 's SkyWay  setting is allow  to localhost

So when i add console.log(peerContexts) in my localhost udonarium
 i would get  this. i can get all room password.

![image](https://user-images.githubusercontent.com/23254376/102198747-b9d00d80-3efd-11eb-834b-70df468a946d.png)

**Comment by TK11235** [comment]
v1.13.0のリリースで修正したためCloseします。
