### ISSUE TITLE
要望・○○さんが入力中です機能

### ISSUE THREAD

**Issue by yadu-ki** [TK11235/udonarium#15]
こんにちは。絵文字バグの際は突然の報告Issueに丁寧な対応をいただきありがとうございました。おかげさまでいつも楽しくユドナリウムを利用しております。

今回は新機能の提案に参りました。
チャットアプリやメッセージングアプリで見かける「発言入力中に他メンバーに対してそれを知らせる機能」です。
タイピング速度に差がある場合や長考・長文入力の際にもやりとりがスムーズになるなど、ユドナリウムでも有用な機能ではないかと考えています。
![screenshot](https://user-images.githubusercontent.com/31821560/41190541-a24b6450-6c1b-11e8-8d63-fba96627695c.png)
![screenshot 2](https://user-images.githubusercontent.com/31821560/41190542-a643e6c2-6c1b-11e8-97c2-ddeb06101ade.png)
このようなUIを想像しています。

プルリクエストでなく恐縮ですが、よろしければご検討ください。

**Comment by TK11235** [comment]
提案ありがとうございます。

提案して頂いている通り一般的な機能ですので、いずれ対応しなければならないと考えています。
まだ実装時期は未定ですが、実装までこのIssueはOpenのまま維持します。

**Comment by TK11235** [comment]
実装したのでIssueをクローズします。
機能はv1.6.0でリリースします。
