### ISSUE TITLE
バグ：「ZIP読込」ボタンで同じZIPファイルを複数回読み込むと、2回目以降のみその内容が追加されない

### ISSUE THREAD

**Issue by tetradice** [TK11235/udonarium#150]
「ZIP読込」ボタンで同じZIPファイルを複数回読み込むと、2回目以降にそのZIP内のオブジェクト（カード、山札など）が追加されないようです。
※ブラウザへのドラッグ＆ドロップであれば、2回目以降も追加が行われます

バージョン1.13.0、PCのChromeブラウザで確認しました。

**Comment by TK11235** [comment]
v1.13.1のリリースで修正したためCloseします。
報告ありがとうございました。
