### ISSUE TITLE
ファイルを指定して共有の追加

### ISSUE THREAD

**Issue by bogytech** [TK11235/udonarium#16]
なかなか良くできたツールで楽しく使わせてもらっています。
現在のところファイル（画像等）の共有にはドラッグ&ドロップでのみ可能なように見えます。
諸事情によりドラッグ&ドロップができない環境で利用した時に困ることがありました。
「ファイルを指定して共有」ボタンのようなものを追加して、ブラウザのファイル選択ウィンドウを開いて指定する方式も追加できないでしょうか？

**Comment by TK11235** [comment]
提案ありがとうございます。

ボタンからファイル選択画面を表示する機能はそのうち実装します。
実装までIssueはOpenのまま維持します。

**Comment by TK11235** [comment]
実装したのでIssueをクローズします。
特に問題が出なければv1.6.0でリリースします。
