### ISSUE TITLE
要望：テーブル上に点と点を結ぶ直線を引く。オリジナルカード作成機能。

### ISSUE THREAD

**Issue by lineling** [TK11235/udonarium#22]
はじめまして。保田と申します。
オンラインセッションの場としてユドナリウムに将来性を感じて、要望を出させていただきました。
マップ上に線を引いて召喚陣を描くTRPG風ボードゲーム『サモンスケート』というゲームをつくっています。そのオンラインセッションの場としてユドナリウムが使えないかと思ったのですが、テーブル上に線を引けないため断念しました。
そのため、要望として、以下の機能を出させていただきます。

・テーブル上のMAP画像の上に直線を引く。
　（フリーハンドでなく、キャラクターが置ける座標を結ぶように縦横斜め線が引ける）
　キャラクターの置ける座標（現在だと１マスにつき９箇所あると思います）にスナップし、ドラッグした始点と終点を結ぶ直線機能があると、画像を用意しなくてもダンジョンマップなども作りやすいため、サモンスケートに限らず汎用性があります。
フリーハンドは容量が多くなると思いますが、直線であれば容量も少ないかと思います。
線の色や幅も複数あるとドアや水の境も再現できて良いのではないでしょうか。
スナップした線は全消しでなく、１マスごとの消しゴム機能があると隠し扉の表示などが便利だと思います。

・オリジナルカード作成機能。
　キャラクターのように画像をアップロードしてオリジナルのトランプ機能がつくれると、インセインなどのTRPGにも便利です。設定が簡単であれば、TCGやカードゲームをつくっている方もユドナリウムを活用したい方は多いと思います。

これは一段階低い要望ではあるのですが…
・射線を確認する
　点と点を結ぶ機能の亜種として、エムブリオマシンなどのゲームを遊ぶ時はキャラクター同士を直線で結んで射線を一時的に表示する機能があると便利だと思いました。地形がぶつかると色が変わればもう最高です。
この機能が実装されればタクティクスオウガのようなゲームを遊べるユドナリウムTRPGをつくりたいと思いました。

参考：サモンスケートhttp://linedline.wixsite.com/yuugakugei/summonskate

開発でご多忙のため、大変かと思いますがご一考いただければ幸いです。

**Comment by TK11235** [comment]
提案ありがとうございます。

> ・テーブル上のMAP画像の上に直線を引く。

機能の汎用性については提案して頂いている通りだと思います。
そのため、お絵描き機能はいつか実装したいと考えているのですが、

- 立体地形との相互作用
- セーブデータでの取り扱い

等の仕様検討が必要なため、今のところ優先度を下げて考えている状態です。
かなり先の話になりそうですが気長にお待ち頂ければ幸いです。

既存機能を使って無理やりにでも実現する場合、

1. 「直線（の描かれた正方形の透過画像）を設定した"高さ0 幅1x1"の平たい地形」を作成してテーブルに配置
2. 同色の直線は回転＆コピーで使い回すことで長い直線を表現

のような方法になるかと思います。

> ・オリジナルカード作成機能。

既存機能で実現できると思います。

テーブル上のコマなどは全て右クリックメニューから編集可能になっています。
カードであれば右クリックメニューの「カードを編集」で編集用の画面が開きますので、そこからカード表裏画像を変更してみて下さい。
（今のところ、編集は1枚ずつです）

> ・射線を確認する

オブジェクト間に直線や矢印を表示できれば確かに便利だろうなとは感じます。
しかし、無いなら無いで何とかなりそうでもあるので優先度は低いかなとも思っています。

**Comment by lineling** [comment]
ご返答頂きありがとうございます。

やはり、線は難しいのですね…現状で再現できる方法を教えていただきありがとうございます。
たしかにこれなら回転とコピーを駆使して再現できると思います。手間をみながら実用的か検討してみようと思います。

すでにカードは画像変更できるのですね。失礼いたしました。
キャラクターのようなカードの画像データ画面がなかったのと、トランプとあるため画像変更は無理かと勘違いしていました。ご指摘いただきありがとうございます。後ほど試そうと思います。

射線は優先度低くなりますよね。

ありがとうございました。ユドナリウムの発展を期待しております。
