### ISSUE TITLE
ダイレクトメッセージ機能についての提案

### ISSUE THREAD

**Issue by kumakaba** [TK11235/udonarium#3]
v1.1.0を触っていて、ダイレクトメッセージ機能について気になった点がありましたので、提案ついでに報告させていただきます。

・自分で打ったダイレクトメッセージが見えない。

メッセージ先にはもちろん見えているのですが、メッセージ元のリアクションが無いため少し不安になります。可能ならメッセージ元にもメッセージを投げてしまって良いと考えます。

・再接続を繰り返すとダイレクトメッセージ先の選択肢がもりもり増える。

再接続後に同じ名前を設定されると先の挙動も相まって更にややこしいことに。接続相手が生きてるかどうかのチェックが必要なのかもしれません。

以上、ご参考になるようであれば幸いです。

**Comment by TK11235** [comment]
報告ありがとうございます。

> ・自分で打ったダイレクトメッセージが見えない。

現象を再現できませんでした。

ダイレクトメッセージは送信元と送信先にそれぞれ表示されるように実装したつもりで、私の環境では今のところ、そのように動作しているように見えます。

可能であれば、現象が起きた時の操作やブラウザコンソールログの内容をお教え頂けるでしょうか。
別のエラーが原因でチャットウィンドの更新が停止している等の可能性を予想しています。

> ・再接続を繰り返すとダイレクトメッセージ先の選択肢がもりもり増える。

こちらは現象を再現できました。
各Peerの接続状態の確認は常に行っているのですが、それとは別に、各プレイヤー情報をテーブルのコマ等と同じ仕組みで共有していることが直接の原因です。

プレイヤー情報の管理方法について修正を検討してみます。

**Comment by kumakaba** [comment]
ご回答・ご検討ありがとうございます。

「自分で打ったダイレクトメッセージが見えない」についてですが、再現を試みましたところ、条件がありました。情報不足で大変申し訳ありません。

・「他のPeerと接続」で接続した場合は正常動作（送信元にもDMが反映）。
・「ルーム機能」で作成した部屋に入ったPeer同士で行うと現象再現（送信元にはDMが表示されない）。

コンソールログは両条件比較しても特に違いが見られず、エラーとなっている様子はありませんでした。ブラウザはChromeとfirefoxで、双方向試しましたが同様の現象となります。

**Comment by TK11235** [comment]
助かります。ダイレクトメッセージの現象再現できました。

ルーム機能の使用有無でPeerIDの構造が異なる仕様なのですが、この構造差分にダイレクトメッセージの表示判定が追従できていないのが原因でした。
表示判定の修正で対応します。

このIssueはそれぞれの修正をコミットしたのちCloseする予定です。
