### ISSUE TITLE
BGM機能の問題報告とSE機能追加要望＋コマの追加機能要望

### ISSUE THREAD

**Issue by kuroikurowo** [TK11235/udonarium#31]
こんにちわ、何度かTRPGで使わせてもらっています。
開発技能が一切無い人間ですが、使用中に発生したBGMの問題に関しての報告と、SE機能の要望です。

MP3データの2秒程度ののSE、ジングルを流そうと再生したところ、ループが断続的に発生するためか、停止ボタンを押しても停止せず、負荷のために参加者全員のチャットログの更新が停止し、別の部屋を立て直すことになりました。

SEやファンファーレのような極端に短いもの、1度流せば十分なもの用に、視聴と同じように1回だけ再生する機能の追加を希望します。
==============================================＝＝＝＝＝＝＝＝＝＝＝＝＝
GitHubやIssuesことが良く分からないので、ルール違反かもしれませんがせっかくなので、他の追加希望要素に関しても。

①キャラクターコマのノート機能の表示の拡大縮小機能
キャラシートから出力したTEXTの内容を、コマの編集で各欄を埋める形式では時間がかかる上に、各要素を編集した章毎に表示しようとすると、画面が埋まってしまい参照が難しくなるため、
ノートにTextをコピー＆ペーストする方法を使いたいのですが、現在のノートでは長文になると全文をほとんど表示できず、参照する際、そこからPLがコピペしてメモ帳に張っており、ほとんど役立っていません。ノートの表示領域のサイズを広げる機能を望みます。
機能名が素人には分からないので、別サイトのものhttps://gyazo.com/00afcab78aa31cbf4a1b2832356a2bc2

②コマの上にカーソルを置いたとき、コマのステータスをオーバレイ表示
①に関連しての機能で、オンラインセッションは時間がかかるものですし、
私の遊んでいる深淵やSW2.0では複数のコマのデータを何度も参照します。数値だけでなく挙動面で複数能力を持たせるのをノートを使わずにコマ編集の機能だけやろうとすると、①と同じように画面がウィンドウで見えなくなります。
これではせっかくの3Dの卓上を見る妨げになります。
故にインベントリ画面で見れない情報をコマのノートの内容をマウスを上に重ねるだけで表示する機能の追加を望みます。

③ログが隠れる
チャットの新しいログが自動でスクロールがされないことがあり、1番新しい内容がチャットの入力欄の下に隠れてしまいます。不便ですので、表示欄とチャット入力欄は分けることを望みます。

④複数振りの機能の追加
「2d+６」を3回降る場合、2d+6を3回入力する必要があります。時間と再入力の手間がかかりますしログがだいぶ進みます。
「3　2d+6」　で一気に2d+6の結果を3回求める機能を望みます。

他にも使っている上で不便な点はありますが、強く要望するのがこの4つです。
文系のプログラミングなどまったく分からない人間の身勝手な要望で申し訳ありません。
やかましい意見となりましたが改善、発展につなげてくださると嬉しいです。

**Comment by TK11235** [comment]
問題報告と提案ありがとうございます。

### ループ再生問題について
報告ありがとうございます。

BGMのループ処理は負荷の高い処理ではなく（※1）、ユーザ間のデータ通信も必要としない仕様になっています。
そのため「ループが連続するので処理が重くなる」という可能性は考え辛く、もしかすると、ループを停止できない問題、負荷が高い問題、チャットログが更新されなく問題はそれぞれ別の問題なのかもしれません。

BGM再生/停止ボタン操作の前後に何かバグが発生した予感がします。

原因を特定したいので、現象が発生した当時の状態についていくつか質問をしても良いでしょうか。
分かっている範囲で良いので回答して頂けると助かります。

- 使用していたブラウザ（Chrome、Safariなど）
- ユドナリウムのバージョン（最新であれば1.6.4）
- 現象をもう一度発生させることは簡単ですか？（特定のMP3ファイルを再生すると必ず異常が発生する、など）
- 現象発生時の参加人数
- チャットログが停止するまでの間、あるいは停止した後、ユドナリウムは操作可能でしたか？処理落ちでガタついたり画面が固まったりしましたか？

(※1 「BGMを終点から始点にループさせる処理」はブラウザの機能を任せています)

### 要望について

提案ありがとうございます。

> SEやファンファーレのような極端に短いもの、1度流せば十分なもの用に、視聴と同じように1回だけ再生する機能の追加を希望します。

機能としてはいずれ実装したいと考えています。気長にお待ち頂けると幸いです。

> ①キャラクターコマのノート機能の表示の拡大縮小機能

ノート機能が見辛いのは指摘の通りだと思います。
ただ、UIの修正はレイアウト制御などの都合から調整が難しい、という状態です。
1.9.0以降にUIの大改修を考えているので、そのタイミングで対応を考えたいです。

> ②コマの上にカーソルを置いたとき、コマのステータスをオーバレイ表示

情報のオーバーレイ表示は、Twitterや #25 で近い内容の提案を貰っています。
必要な機能だと思いますので、早めに対応したいです。

> ③ログが隠れる

自動スクロールは、過去ログ参照中に強制スクロールされてしまうことを防ぐために「スクロールバーがチャットログ最下部に到達しているとき」のみ自動スクロールする仕様になっています。
自動スクロールの発生条件（スクロールバーの位置）を緩和して、ほどよく自動スクロールするように修正してみます。

（※表示欄とチャット入力欄を分けても、結局、自動スクロールしなければ見切れている部分のログは読めないのでは？と思っています）

> ④複数振りの機能の追加

無くても何とかなる機能かな、と思っています。
他の作業を優先して優先度低めの状態です。

**Comment by kuroikurowo** [comment]
状況の報告です
①ブラウザはchromが最低4名　火狐が1名のようでした
②報告の1週間前にお借りした時でしたので最新状態のはずです。
③部屋内に1名しか居ない状態では発生しませんでしたが、5名の状態では再発しました。
④発生時は部屋内に10名～8名が居て、全員同じ状態になり、部屋を立て直しました。
⑤テーブル上のコマなどは正常にリンクしているようでしたが、チャットログが更新されていない人、
時間が経ってから更新される人などが居ました。

**Comment by TK11235** [comment]
私の環境では特に問題ないようなのでCloseします。
将来的に再発が確認された場合、改めてIssueをOpenして対応します。
