### ISSUE TITLE
あらゆる詳細パネルのタイトルが「キャラクターシート」になっている

### ISSUE THREAD

**Issue by yadu-ki** [TK11235/udonarium#33]
現状、

- マップマスク
- 地形
- カード（山札ではなく、一枚のカード）
- 共有メモ

など明らかにキャラクターシートではないものであっても、「詳細を表示」した際のタイトルバーが「キャラクターシート」になっています。

セッション準備中やユドナリウム自体のコードをいじっている時は気になるものの、実際にセッションしている間に気になった覚えが（私には）ないため、対応優先度は低いようにも思いますが……一応確認していただければと思います。

よろしくお願いします。

**Comment by TK11235** [comment]
指摘ありがとうございます。

データ項目の表示を全て`GameCharacterSheetComponent`に任せている故の挙動です。
動作的には問題無い状態ですが、指摘の通りタイトルバーの表示は修正した方が良いですね。

修正までIssueはOpenのまま維持します。

**Comment by TK11235** [comment]
修正したのでIssueをクローズします。
v1.7.1のリリースで反映されます。
