### ISSUE TITLE
インベントリの「並び順」を使用しても昇順、降順にならない

### ISSUE THREAD

**Issue by usaturn** [TK11235/udonarium#37]
v1.7.0 の「インベントリ並び順序の設定機能」ですが、昇順、降順を選択してもうまく並び替えができないようです。
クローズした issue にも見当たらないようですので issue を上げました。

![2018-11-24_01h24_39](https://user-images.githubusercontent.com/1503215/48953504-6a6ebb80-ef89-11e8-8a09-6b78c0a4a1e2.png)

**Comment by usaturn** [comment]
本件、「通常」等なら並び替えが可能ですが、「リソース」の並べ替えをサポートされていない、という事でしょうか。

**Comment by TK11235** [comment]
返信が遅くなりました。
報告ありがとうございます。

現状の仕様ではリソースの「最大値」を基準に並び替えが行われます。

リソースの「現在値」で並び替えを実行できるようにすると、並び順の変化とスライダー操作が干渉してしまうので暫定的に今の仕様にしていました。
しかし、チャットパレットでは「現在値」を参照する仕様なので、操作性の問題はともかくとして統一した方が混乱は少なそうですね。

v1.7.1で修正します。
修正までIssueはOpenのまま維持します。

**Comment by usaturn** [comment]
v1.7.1 でリソースの現在値で並び替えが実行される事を確認しました。ありがとうございました。
