### ISSUE TITLE
チャットパレットでコメントアウトできるようにする要望

### ISSUE THREAD

**Issue by usaturn** [TK11235/udonarium#41]
チャパレに入力する際、先頭列に `#` 等のコメント記号を入れ、下記の効果を出す事を検討お願いします。

- コメント行の色を薄くする等、視覚的にコメントである事をわかりやすくする
- コメント行を選択しても SEND の部分に入力されない

よろしくお願いします。

**Comment by TK11235** [comment]
反応が遅くなりました。
提案ありがとうございます。

視覚表現と入力制御はあったほうが便利だと思いますが、無いと致命的に困る、という問題でもないかなと感じます。
実装するとしても優先度は低いかな、というのが今の所の考えです。

**Comment by usaturn** [comment]
ご検討ありがとうございます！
仰る通り、無いと困るという類いの要望ではありませんので、バックログの片隅にでもひっそりと置いて頂けると幸いです。

という事でクローズ致します。
