### ISSUE TITLE
地形・マップマスクの上でも右クリックで「キャラクターを作成」できるようにする要望

### ISSUE THREAD

**Issue by karaagee** [TK11235/udonarium#44]
連投すみません、もう1つだけ要望を出させてください。
地形・マップマスクの上で右クリックしたとき、メニュー「キャラクターを作成」が選択でき、それらの上にコマを作成できないかという要望です。
当方がユドナリウムを利用するときマップ上に地形・マップマスクを多用するのですが、その際いつも用いている右クリックで目的の場所にコマを作成できず少しだけ手間に感じることがあるからです。

しかし既に画面の左メニューに代用となる「キャラ作成」コマンドがありますので、この件は優先度低めのものかと思われます。
アップデートが一通り終わり、時間の空いているときで構いませんので、処理が煩雑で無ければ実装を御願いしたい次第です。

**Comment by TK11235** [comment]
反応が遅くなりました。
提案ありがとうございます。

地形機能を利用するのであれば、出来て然るべき機能ですね。
実装しようと思いますので、実装完了までIssueはOpenのまま維持してください。

右クリックメニューの項目修正だけで何とかなる筈なのでv1.8.0で実装できると思います。

**Comment by karaagee** [comment]
確認しました。v1.8.0での実装ありがとうございます。
実装完了されましたので、このIssueはClosedに致します。
