### ISSUE TITLE
キャラコマ画像とチャットアイコンについて

### ISSUE THREAD

**Issue by dx3maru** [TK11235/udonarium#47]
初めまして、ユドナリウム使わせてもらってます。
ユドナリウムではキャラコマに画像を設定すると画像全体が見えますので、見栄えも良いしということで全身画像をよく設定するのですが、その場合チャットにてアイコンが判別し辛いです。
もし良ければ、キャラコマ画像をチャットアイコンに設定するまでに画像を切り取れる機能（どこからどこまでをアイコンとする処理）を任意で入れてもらえませんでしょうか。

**Comment by TK11235** [comment]
提案ありがとうございます。
反応が遅くなりました。

チャットに表示する画像をアイコン風に切り抜く修正を 9a3e39576f33d728edbfe5cf5022ef56d683d350 で行いました。
切り抜き処理は自動ですが、大抵の場合はアイコンとして自然に表示されるかと思います。

アイコンの細かい設定機能は立ち絵機能等と合わせていつか実装したいと考えています。
気長にお待ち頂けると助かります。

9a3e39576f33d728edbfe5cf5022ef56d683d350 の修正はv1.8.3のリリースで反映されます。
リリースまでIssueはOpenのまま維持します。

**Comment by dx3maru** [comment]
確認しました。
本当にありがとうございます！
