### ISSUE TITLE
チャットの文字色に関する要望

### ISSUE THREAD

**Issue by karaagee** [TK11235/udonarium#48]
こんにちは、 Closed Issuesでも触れられていなかった要望を提出しに参りました。
任意の文字色でチャットウィンドウに発言できないか、という要望です。

理由
①どのキャラクターの発言かをより区別しやすくするため
②描写中、文字色を変えて演出を行いたい場面があるため
③外部ツールでログをHTMLに書き出すとき、文字列が黒一色で個人的に寂しい

どのような機能・見た目にするのか具体的な提案は無いのですが、どどんとふの「チャット文字設定 -> 文字色」のようなものを想定しての提案です。
もし時間がございましたら、ご一考いただければ幸いです。

**Comment by TK11235** [comment]
提案ありがとうございます。

> ①どのキャラクターの発言かをより区別しやすくするため

悩みどころではあるのですが、
発言者の判別を目的としたチャットの色設定はあまり実装したくないな、と思っています。

理由は大体以下の2つです。

- 色指定による発言者判別はテキストオンリーのUIでは必要になっても、アイコン等を含むUIなら不要なのでは。
- UIの見た目がカラフルになり過ぎて見た目が汚くなるような予感がする。

> ②描写中、文字色を変えて演出を行いたい場面があるため

演出目的の機能として考えた場合は、色指定はあっても良いのかなとは思います。
ただ、現状のユドナリウムは「実用上必須となる機能から優先して実装する」という方針で開発を行っており、演出機能は実装するとしても優先度は低めになります。

>③外部ツールでログをHTMLに書き出すとき、文字列が黒一色で個人的に寂しい

外部ツールの機能や開発状況を私の方で把握するのは難しいので、これについては何も言えません。

**Comment by karaagee** [comment]
返信ありがとうございます。
かしこまりました、①②はともかく③は完全に無関係の問題でした、失礼しました。
実用上必須となる機能を優先という方針、了解いたしました。
それでは此方のIssueはClosedとさせて頂きます。
