### ISSUE TITLE
2回繰り返して発言できるようにする要望

### ISSUE THREAD

**Issue by Geleboo** [TK11235/udonarium#49]
初めまして、いつも利用させていただいてますゲレブーといいます。お世話になってます。

要望したいのは、「同じ発言を2度繰り返す」機能の実装です。私はD&Dを中心に遊んでいますが、D&Dでは有利判定の場合ダイス2個を振っていい方の目を採用する、不利判定の場合は悪い方の目を採用するというルールがあるので、頻繁に同じダイス・ロールを2回繰り返します。

これをどどんとふでは発言の前に「2+space」つまり、「2 1d20+0 イニシアチブロール」と打つと

DungeonsAndDoragons : (1D20+0) → 10[10]+0 → 10　イニシアチブロール　＃1
DungeonsAndDoragons : (1D20+0) → 14[14]+0 → 14　イニシアチブロール　＃2

のように結果を返すことで対応しています。チャットパレットなら2回クリックするだけでしょう、と言われると身も蓋もないのですが、常に2回振ることが決まっている場合もあるのでセッションがスムーズに進みますし、1回目のダイスロールで目標値に達してしまうと2回目が興ざめになるのも避けたいところです。「2b20」のようにbダイスを使えば、任意の個数のダイス結果を返してはくれるのですが、後ろに四則演算をつけると現状では無視されるので使いにくいです。

他のTRPGのことがわからないのですが、もしかしたら2だけではなく、任意の数字（「4 1d20+4 攻撃」や「10 1d20+3　enemyの数」でも可能）での実装がよりベターなのかもしれません。ご検討いただければ幸いです。

**Comment by TK11235** [comment]
反応が遅くなりました。
提案ありがとうございます。

> D&Dでは有利判定の場合ダイス2個を振っていい方の目を採用する、不利判定の場合は悪い方の目を採用するというルールがあるので、頻繁に同じダイス・ロールを2回繰り返します。

どのような場面で連続ダイスロールが必要になるのか把握できました。ありがとうございます。

チャットパレットから2回送信する方式だと、1回分余計な送信ログが残ってしまうので判定結果の視認性が良くない気がしますね。
このIssueの提案の通り、連続でダイスボットを実行する機能を実装する方が妥当だと思います。

> 任意の数字（「4 1d20+4 攻撃」や「10 1d20+3　enemyの数」でも可能）での実装がよりベターなのかもしれません。

"必ず2回だけ"に制限する理由も特に無いので、任意の回数を指定して連続ダイスロールを行えるように実装を考えてみます。
（どどんとふに実装されている同様の機能では回数の指定ができたような気がします）

---

v1.9.0での実装を予定しています。
実装までこのIssueはOpenのまま維持して下さい。

**Comment by Geleboo** [comment]
実装ありがとうございました。とても利便性が向上しました！これでCloseします。
