### ISSUE TITLE
チャットパレットの反映先タブに関する要望

### ISSUE THREAD

**Issue by NktAts** [TK11235/udonarium#54]
チャットパレットはチャット画面とは別に反映先タブ・発話対象の設定を持っていますが、これが原因で

1.チャットパレットを開く
2.反映先タブの設定を忘れたまま発話内容を記述→発話
3.結果として、望まないタブに発話してしまう（大抵はメインタブ）

という事態が多発し不便を感じています。

　可能であれば、「現在のチャットウィンドウの設定で発話」のチェックボックスを設けるなどの形で、現在表示しているタブ・発話対象に従う形で発話する設定を作っていただけないでしょうか。
　その場合、チャットウィンドウを開いていない場合には、チャットパレットの設定に従う形で発話する形式で問題ありません。

　ご一考いただければ幸いです。よろしくお願いします。

**Comment by TK11235** [comment]
提案ありがとうございます。

チャットパレットが誤送信しやすい仕様になっているのはこちらでも認識しています。
v1.9.0以降の更新でUIを全体的に改善する予定ですので、気長にお待ち下さい。

#### 提案して貰っている改善案について

> 可能であれば、「現在のチャットウィンドウの設定で発話」のチェックボックスを設けるなどの形で、現在表示しているタブ・発話対象に従う形で発話する設定を作っていただけないでしょうか。

チャットウィンドウは複数開いて別々のタブを同時に表示できます。

そのため、チェックボックスだけでは「どのチャットウィンドウの状態に従うべきか」を判定するのが難しく、結果的に上手くいかない予感がします。

具体的な改善方法はこれから検討する状況ですが、「ボタンや設定を増やす」よりは「UIの状態を認識しやすい・間違え辛い表示方法を考える」という方向で改善したいと思っています。

※チャットパレットのUI改善についての話題は #50 も参照

---

改善までIssueはOpenのまま維持します。

**Comment by TK11235** [comment]
v1.9.0のリリースでチャットパレットUIを更新しました。
チャットウィンドウと見た目を統一し、元の状態よりは送信先タブを間違え辛くなったかなと思います。

![スクリーンショット (809)](https://user-images.githubusercontent.com/30261850/60023370-a3624080-96d0-11e9-90ac-34affce2b32e.png)

今回の更新は「とりあえず元よりはマシにする」という作業の結果であり、今後も継続して改善が必要です。

チャットパレットに関する話題は #50 に一本化した方が良い気がするので一旦このIssueをクローズします。
追加の検討やアイデアの議論は #50 の方にお願いします。
