### ISSUE TITLE
山札から引いたカードがマップに表示されない不具合

### ISSUE THREAD

**Issue by telete921** [TK11235/udonarium#57]
ver1.9実装おめでとうございます、制作お疲れ様でした。
今回はトランプについての不具合ですが

山札を作成して、山札からカードを引くと
引いたカードがマップ上に表示されない事があります。

・「ダブルクリックで」「右クリック＆１枚引く」のどちらでも発生する
・山札枚数は減少している
・２つ以上の山札をドラッグドロップすると正常（に見える）動きをする。

という現象を確認しました
よろしくお願いします。

**Comment by telete921** [comment]
カード修正お疲れ様です、重ねて報告ですみません。

「コマ詳細」→「編集切り替え」から
リソースのタグ名（HP・MPなど）を変更すると
マウスオーバーで該当のリソースが表示されない、
HPやMPなど初期設定の名前に戻すと表示される、という事があります

発生せず、正常に表示される事もあるのですが
⊖（丸にマイナス）ボタンで「リソース」「情報」・・・などの項目をすべて消し
新しいリソースを作るとほぼ確実に発生するようです

報告はさせて頂きますが無理せず、よろしくお願いします。

**Comment by telete921** [comment]
すみません、この件についてですが
インベントリに追加したい項目名を追加する事で、表示する事に成功しました
お手数おかけしてすみませんでした。

> カード修正お疲れ様です、重ねて報告ですみません。
> 
> 「コマ詳細」→「編集切り替え」から
> リソースのタグ名（HP・MPなど）を変更すると
> マウスオーバーで該当のリソースが表示されない、
> HPやMPなど初期設定の名前に戻すと表示される、という事があります
> 
> 発生せず、正常に表示される事もあるのですが
> ⊖（丸にマイナス）ボタンで「リソース」「情報」・・・などの項目をすべて消し
> 新しいリソースを作成、「HP」以外のタグ名をつけるとほぼ確実に発生するようです
> 
> 報告はさせて頂きますが無理せず、よろしくお願いします。

**Comment by TK11235** [comment]
返信が遅くなりました。
報告ありがとうございました。

このIssueはv1.9.1で解決済みのためクローズします。

---
仕様について混乱させてしまったようです。

キャラクターのマウスオーバー表示はインベントリの表示項目設定と同期する仕様です。
カード、山札、ダイスシンボルについては設定したタグ項目が全て表示されます。

バグだと感じた要素については気にせずIssueに挙げてもらって問題ありません。
私が気付いていないバグであれば修正が必要ですし、問題ない場合も記録として残ることに価値があります。
