### ISSUE TITLE
インベントリ・ポップアップに不明なリソーススライダーが表示される不具合

### ISSUE THREAD

**Issue by NktAts** [TK11235/udonarium#58]
Ver1.9の開発、ありがとうございます。
ポップアップUIのおかげで、いろいろとできることが増えそうです。

本題ですが、Ver1.9.1で確認された不具合です。
インベントリを表示したとき、一部のキャラクター情報にて、キャラクター詳細に含まれない（当然、インベントリ項目にも含まれない）不明なリソーススライダーが表示されます。ポップアップUIにも、同様に表示されます。

![不明のリソーススライダー](https://user-images.githubusercontent.com/48486798/58740923-a4e07600-844e-11e9-803a-abd52d744169.png)

上記スクリーンショット赤枠の部分です。

キャラクター全員に表示されるわけではないようで、表示される条件は不明です。
不明なリソーススライダーを操作してみましたが、連動してどこかの数値が変わっているようには見えませんでした。

事象が発生するルームデータも併せて提供します。
（参加者への配慮のため、画像とチャットログを削除しています。この状態でも不具合の発生を確認しています。）

[守りたいもの、なすべきこと_ユドナリウム_20190522_bugcheck.zip](https://github.com/TK11235/udonarium/files/3243211/_._20190522_bugcheck.zip)

**Comment by TK11235** [comment]
返信が遅くなりました。
報告ありがとうございました。

このIssueはv1.9.1で解決済みのためクローズします。

---
不自然な表示の原因は「インベントリの表示項目設定の最後尾の空白文字」が表示タグ項目の１つとしてカウントされていたからでした。

（表示されている「不明なリソーススライダー」の正体は、キャラクターシートに含まれている「タグ名が"空"の項目」が表示されてしまったものです）

本件、セーブデータを添付して頂いたおかげで原因の特定と修正を非常にスムーズに行えました。
ありがとうございました。
