### ISSUE TITLE
山札に含まれるカードの座標値に関する不具合

### ISSUE THREAD

**Issue by TrpgRoki** [TK11235/udonarium#69]
いつも素敵なツールをありがとうございます。
1.9.1はプレイヤーからも「とても使いやすくなった」と好評です。
その1.9.1でひとつ不具合を確認しましたのでご報告いたします。

[不具合の内容]
山札を移動させたとき、山札に含まれるカードの座標は元の位置の値のままとなってしまうようです。
そのため、例えば「重なったカードで山札を作る」で作った山札（A）を別の座標に移動したのちに、山札（A）があった座標に別のカードを配置して「重なったカードで山札を作る」を実行すると、山札（A）のカードを含めて新たな山札（B）を作ってしまいます。
この状況下で山札（B）に何らかの操作を行うと、山札（A）はカード枚数0枚となります。

なお、「すべて表にする」「すべて裏にする」「すべて正位置にする」「シャッフル」などの操作を行うと座標値は更新されます。

**Comment by TK11235** [comment]
報告ありがとうございます。

バグでしたので修正しました。
v1.9.2のリリースで修正を反映していますのでこのIssueをクローズします。

バグ原因は「山札に取り込むべきカードの取捨選択」の判定処理が間違っていた為でした。
（他の山札のカードは取り込まない、という処理が正しく動作していなかった）

#### 補足
山札とカードの座標更新タイミングについてですが、これは意図的な仕様として実装しています。

- 山札の移動に合わせて内包する全てのカードの座標を更新してしまうと、山札の枚数に比例してデータ更新量が増加してしまう
- 画面表示の性質上、山札の座標情報のみ更新できれば十分

であるため、山札の座標とカードの座標の更新タイミングは必ずしも一致しない仕様になっています。

カードの座標は「座標更新の必然性があるか、カードに関する別の情報を更新するついで」に更新する仕様です。
