### ISSUE TITLE
ユドナリウムのiPhoneへの対応について

### ISSUE THREAD

**Issue by secundusterra** [TK11235/udonarium#82]
ユドナリウム(v1.10.0)のご開発ありがとうございます。
タッチ操作にご対応いただき、スマートフォンでの使用が可能になったことを大変ありがたく思っております。

一点質問ですが、スマートフォンの対応はAndroidのみでしょうか？
iPhone、iPad等ではどのブラウザで検証しても、真っ白な画面から動きません。
ツイッター等で検索してみると、他の方も同じ状況のようです。

お忙しい中大変恐縮ですがご回答のほどよろしくおねがいいたします。

**Comment by TK11235** [comment]
報告ありがとうございます。

私の手元にiOS系のデバイスが無いので動作確認はできていないのですが
原因の目星が付いているのでv1.10.1で修正します。

v1.10.1のリリースまでIssueはOpenのまま維持します。

**Comment by TK11235** [comment]
完全な動作確認までは行えていませんが、画面表示については修正したのでIssueをクローズします。
